### ISSUE TITLE
[CHALLENGE] - Hashing without a salt

### ISSUE THREAD

**Issue by luisfontes19** [DamnVulnerableCryptoApp/DamnVulnerableCryptoApp#22]
Use something like sha256 to encrypt passwords without a salt. 
Find a nice dictionary with pre computed hashes for help documentation

The scenario could be an sql file with dump of a DB with some credentials (but it looks like weak hash)
Other idea could be the hashed version of the password used in a cookie to manage authentication.

in documentation show the differences between bruteforce an hash with and withouth the salt. The difference in time. 

Always use passwords from the TOP 500, just to make it fast

**Comment by AVBC-Sec** [comment]
For this example, and to make it look like a real attack/vulnerability, you could make it like a DB dump full of hashes and have 5 users with the same password, including the Admin. To make it easier, the admin password should be 123456.

This makes the exercise simple and manageable. You only need to notice the same hash on several users and know what are the most common passwords.

**Comment by luisfontes19** [comment]
@AVBC-Sec sounds good. 
We already have a similar scenario in the weak hashing challenge, a DB dump with some hashed credentials. 
So I would recommend having a similar case but witha PHPmyadmin like system, where you can query some tables and eventually see the user hashes.  Just to try to make it a little bit different.


Also the action to submit the solution to the challenge could be logging into that system as admin

**Comment by luisfontes19** [comment]
Will not implement this for now...

Weak hashing doesn't use salt either, and as an easy and reliable challenge we should not use
