### ISSUE TITLE
every time same issue 

### ISSUE THREAD

**Issue by Expertasif** [DamnVulnerableCryptoApp/DamnVulnerableCryptoApp#85]
Describe clearly what is your issue, and what you expect from an answer of this issue.
Provide as much information as possible.
![npm](https://user-images.githubusercontent.com/16167241/100759516-b2e1cf00-3416-11eb-930f-22822532bfd9.png)

**Comment by luisfontes19** [comment]
Hi @Expertasif,

The npm scripts were a mess, I just did a new commit for kinda improve it.
So get the latest version and run:

```bash
npm install -g yarn npx
npm run install-with-deps
npm run start
```

**Comment by Expertasif** [comment]
again same issue 
![2020-12-01](https://user-images.githubusercontent.com/16167241/100785568-d6b50d00-3436-11eb-91b3-ff6581a1cef5.png)

**Comment by luisfontes19** [comment]
Can you add the output of 'npm run build-with-deps' here?

Also, from the name where you have the project, you probably have the wrong vulnerable app... The vulnerable app for smart contracts is [DamnVulnerableDefi](https://www.damnvulnerabledefi.xyz/)

**Comment by luisfontes19** [comment]
closing due to lack of response
